//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DicomViewerDemo.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DicomViewerDemo.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string DEMOSCOMMONCODE_ABOUT {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has invalid format..
        /// </summary>
        internal static string DEMOSCOMMONCODE_ARG0_HAS_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ARG0_HAS_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the panel if current color must be changed..
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_ON_THE_PANEL_IF_CURRENT_COLOR_MUST_BE_CHANGED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_ON_THE_PANEL_IF_CURRENT_COLOR_MUST_BE_CHANGE" +
                        "D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button if the current color must be changed..
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_THE_BUTTON_IF_THE_CURRENT_COLOR_MUST_BE_CHANGED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_THE_BUTTON_IF_THE_CURRENT_COLOR_MUST_BE_CHAN" +
                        "GED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button if the current color must be set to the default color..
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_THE_BUTTON_IF_THE_CURRENT_COLOR_MUST_BE_SET_TO_THE_DEFAULT_COLOR {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_CLICK_THE_BUTTON_IF_THE_CURRENT_COLOR_MUST_BE_SET_" +
                        "TO_THE_DEFAULT_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click on the panel if the current color must be changed..
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_DOUBLE_CLICK_ON_THE_PANEL_IF_THE_CURRENT_COLOR_MUST_BE_CHANGED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_DOUBLE_CLICK_ON_THE_PANEL_IF_THE_CURRENT_COLOR_MUS" +
                        "T_BE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find reached the starting point of the search..
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_FIND_REACHED_THE_STARTING_POINT_OF_THE_SEARCH {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_FIND_REACHED_THE_STARTING_POINT_OF_THE_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified text was not found:
        ///{0}.
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_THE_SPECIFIED_TEXT_WAS_NOT_FOUNDRNARG0 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_THE_SPECIFIED_TEXT_WAS_NOT_FOUNDRNARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree View Search Control.
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_TREE_VIEW_SEARCH_CONTROL {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_TREE_VIEW_SEARCH_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree View Search Control.
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_TREE_VIEW_SEARCH_CONTROL_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_TREE_VIEW_SEARCH_CONTROL_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Name.
        /// </summary>
        internal static string DEMOSCOMMONCODE_CUSTOMCONTROLS_VALUE_NAME {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_CUSTOMCONTROLS_VALUE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file can not be added to the series because the file does not belong current series..
        /// </summary>
        internal static string DEMOSCOMMONCODE_DICOM_THE_FILE_CAN_NOT_BE_ADDED_TO_THE_SERIES_BECAUSE_THE_FILE_DOES_NOT_BELONG_CURRENT_SERIES {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_DICOM_THE_FILE_CAN_NOT_BE_ADDED_TO_THE_SERIES_BECAUSE_THE_FILE_DO" +
                        "ES_NOT_BELONG_CURRENT_SERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file can not be added to the series because the file does not belong current study..
        /// </summary>
        internal static string DEMOSCOMMONCODE_DICOM_THE_FILE_CAN_NOT_BE_ADDED_TO_THE_SERIES_BECAUSE_THE_FILE_DOES_NOT_BELONG_CURRENT_STUDY {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_DICOM_THE_FILE_CAN_NOT_BE_ADDED_TO_THE_SERIES_BECAUSE_THE_FILE_DO" +
                        "ES_NOT_BELONG_CURRENT_STUDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_ERROR {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_ERROR_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ERROR_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_ERROR_ALT2 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ERROR_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_ERROR_ALT3 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_ERROR_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Save the measurement annotations to a file.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING__SAVE_THE_MEASUREMENT_ANNOTATIONS_TO_A_FILE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING__SAVE_THE_MEASUREMENT_ANNOTATIONS_TO_A_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DICOM Data Element....
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ADD_DICOM_DATA_ELEMENT {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ADD_DICOM_DATA_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DICOM Sequence Item.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ADD_DICOM_SEQUENCE_ITEM {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ADD_DICOM_SEQUENCE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DicomAnnotatedViewerTool first..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ADD_DICOMANNOTATEDVIEWERTOOL_FIRST {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ADD_DICOMANNOTATEDVIEWERTOOL_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Measure.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ANGLE_MEASURE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ANGLE_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Annotations(*.vsabm)|*.vsabm|XMP Annotations(*.xmpm)|*.xmpm|All Formats(*.vsabm;*.xmpm)|*.vsabm;*.xmpm.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_BINARY_ANNOTATIONSVSABMVSABMXMP_ANNOTATIONSXMPMXMPMALL_FORMATSVSABMXMPMVSABMXMPM {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_BINARY_ANNOTATIONSVSABMVSABMXMP_ANNOTATIONSXMPMXMPMALL_FO" +
                        "RMATSVSABMXMPMVSABMXMPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Annotations|*.vsabm|XMP Annotations|*.xmpm.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_BINARY_ANNOTATIONSVSABMXMP_ANNOTATIONSXMPM {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_BINARY_ANNOTATIONSVSABMXMP_ANNOTATIONSXMPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find encoder for &apos;{0}&apos;..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_CAN_NOT_FIND_ENCODER_FOR_ARG0 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_CAN_NOT_FIND_ENCODER_FOR_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find encoder for &apos;{0}&apos;..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_CAN_NOT_FIND_ENCODER_FOR_ARG0_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_CAN_NOT_FIND_ENCODER_FOR_ARG0_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm overwrite.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_CONFIRM_OVERWRITE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_CONFIRM_OVERWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Compression.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_BEST_COMPRESSION {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_BEST_COMPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Speed.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_BEST_SPEED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_BEST_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_FAST {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_FAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important: some data from annotations will be lost. Do you want to continue anyway?.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_IMPORTANT_SOME_DATA_FROM_ANNOTATIONS_WILL_BE_LOST_DO_YOU_WANT_TO_CONTINUE_ANYWAY {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_IMPORTANT_SOME_DATA_FROM_ANNOTATIONS_WILL_" +
                        "BE_LOST_DO_YOU_WANT_TO_CONTINUE_ANYWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_NORMAL {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_NORMAL_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_NORMAL_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_NORMAL_ALT2 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_NORMAL_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile height must be multiple 16..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_TILE_HEIGHT_MUST_BE_MULTIPLE_16 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_TILE_HEIGHT_MUST_BE_MULTIPLE_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile width must be multiple 16..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_TILE_WIDTH_MUST_BE_MULTIPLE_16 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_TILE_WIDTH_MUST_BE_MULTIPLE_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_VALUE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_VALUE_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_VALUE_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_VALUE_ALT2 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_VALUE_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_VALUE_ALT3 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_VALUE_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_VALUE_ALT4 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_VALUE_ALT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_WARNING {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_DIALOGS_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists. Overwrite it?.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_CODECS_FILE_ARG0_ALREADY_EXISTS_OVERWRITE_IT {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_CODECS_FILE_ARG0_ALREADY_EXISTS_OVERWRITE_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {DecoderName} - decoder name
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_DECODERNAME_DECODER_NAMERN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_DECODERNAME_DECODER_NAMERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Metadata Editor.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_DICOM_METADATA_EDITOR {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_DICOM_METADATA_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Metadata Viewer.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_DICOM_METADATA_VIEWER {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_DICOM_METADATA_VIEWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {DirectoryName} - directory name
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_DIRECTORYNAME_DIRECTORY_NAMERN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_DIRECTORYNAME_DIRECTORY_NAMERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse Measure.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ELLIPSE_MEASURE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ELLIPSE_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter string values (value per line).
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ENTER_STRING_VALUES_VALUE_PER_LINE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ENTER_STRING_VALUES_VALUE_PER_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ERROR {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ERROR_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ERROR_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ERROR_ALT2 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ERROR_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_ERROR_ALT3 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_ERROR_ALT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_EXAMPLESRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_EXAMPLESRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;File {Filename}, page {PageNumber}&apos;
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_FILE_FILENAME_PAGE_PAGENUMBERRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_FILE_FILENAME_PAGE_PAGENUMBERRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Filename} - filename without directory
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_FILENAME_FILENAME_WITHOUT_DIRECTORYRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_FILENAME_FILENAME_WITHOUT_DIRECTORYRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focused.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_FOCUSED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_FOCUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focused Image Appearance Settings.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_FOCUSED_IMAGE_APPEARANCE_SETTINGS {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_FOCUSED_IMAGE_APPEARANCE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {FullFilename} - full filename
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_FULLFILENAME_FULL_FILENAMERN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_FULLFILENAME_FULL_FILENAMERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hovered.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_HOVERED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_HOVERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Measure Tool.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGE_MEASURE_TOOL {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGE_MEASURE_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Measure Tool.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGE_MEASURE_TOOL_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGE_MEASURE_TOOL_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image measure tool settings.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGE_MEASURE_TOOL_SETTINGS {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGE_MEASURE_TOOL_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ImageBitsPerPixel} - source image bits per pixel.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGEBITSPERPIXEL_SOURCE_IMAGE_BITS_PER_PIXEL {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGEBITSPERPIXEL_SOURCE_IMAGE_BITS_PER_PIXEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ImageHeightPx} - source image height, in pixels
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGEHEIGHTPX_SOURCE_IMAGE_HEIGHT_IN_PIXELSRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGEHEIGHTPX_SOURCE_IMAGE_HEIGHT_IN_PIXELSRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ImageHRes} - source image horizontal resolution, in DPI
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGEHRES_SOURCE_IMAGE_HORIZONTAL_RESOLUTION_IN_DPIRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGEHRES_SOURCE_IMAGE_HORIZONTAL_RESOLUTION_IN_DPIRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ImageIndex} - image index, in image collection
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGEINDEX_IMAGE_INDEX_IN_IMAGE_COLLECTIONRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGEINDEX_IMAGE_INDEX_IN_IMAGE_COLLECTIONRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ImageNumber} - image number, in image collection
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGENUMBER_IMAGE_NUMBER_IN_IMAGE_COLLECTIONRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGENUMBER_IMAGE_NUMBER_IN_IMAGE_COLLECTIONRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ImageSizeMpx} - source image size, in megapixels
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGESIZEMPX_SOURCE_IMAGE_SIZE_IN_MEGAPIXELSRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGESIZEMPX_SOURCE_IMAGE_SIZE_IN_MEGAPIXELSRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ImageVRes} - source image vertical resolution, in DPI
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGEVRES_SOURCE_IMAGE_VERTICAL_RESOLUTION_IN_DPIRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGEVRES_SOURCE_IMAGE_VERTICAL_RESOLUTION_IN_DPIRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ImageWidthPx} - source image width, in pixels
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_IMAGEWIDTHPX_SOURCE_IMAGE_WIDTH_IN_PIXELSRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_IMAGEWIDTHPX_SOURCE_IMAGE_WIDTH_IN_PIXELSRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DicomDateTime format..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_INVALID_DICOMDATETIME_FORMAT {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_INVALID_DICOMDATETIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Measure.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_LINE_MEASURE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_LINE_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines Measure.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_LINES_MEASURE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_LINES_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of predefined format variables:
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_LIST_OF_PREDEFINED_FORMAT_VARIABLESRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_LIST_OF_PREDEFINED_FORMAT_VARIABLESRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Measurements....
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_LOAD_MEASUREMENTS {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_LOAD_MEASUREMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the measurement annotations from a file.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_LOAD_THE_MEASUREMENT_ANNOTATIONS_FROM_A_FILE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_LOAD_THE_MEASUREMENT_ANNOTATIONS_FROM_A_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Properties....
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_MEASUREMENT_PROPERTIES {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_MEASUREMENT_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement settings.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_MEASUREMENT_SETTINGS {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_MEASUREMENT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_NORMAL {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Focused Image Appearance Settings.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_NOT_FOCUSED_IMAGE_APPEARANCE_SETTINGS {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_NOT_FOCUSED_IMAGE_APPEARANCE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_NOT_READY {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PageIndex} - page index, in source image file
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_PAGEINDEX_PAGE_INDEX_IN_SOURCE_IMAGE_FILERN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_PAGEINDEX_PAGE_INDEX_IN_SOURCE_IMAGE_FILERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PageLabel} - page label
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_PAGELABEL_PAGE_LABELRN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_PAGELABEL_PAGE_LABELRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PageNumber} - page number, in source image file
        ///.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_PAGENUMBER_PAGE_NUMBER_IN_SOURCE_IMAGE_FILERN {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_PAGENUMBER_PAGE_NUMBER_IN_SOURCE_IMAGE_FILERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties....
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_PROPERTIES {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all measurements of focused image.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_REFRESH_ALL_MEASUREMENTS_OF_FOCUSED_IMAGE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_REFRESH_ALL_MEASUREMENTS_OF_FOCUSED_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Measurements.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_REFRESH_MEASUREMENTS {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_REFRESH_MEASUREMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Measurements....
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_SAVE_MEASUREMENTS {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_SAVE_MEASUREMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_SELECTED {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_SEQUENCE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_SEQUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show properties form for focused measurement annotation.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_SHOW_PROPERTIES_FORM_FOR_FOCUSED_MEASUREMENT_ANNOTATION {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_SHOW_PROPERTIES_FORM_FOR_FOCUSED_MEASUREMENT_ANNOTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show properties form for image measure tool.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_SHOW_PROPERTIES_FORM_FOR_IMAGE_MEASURE_TOOL {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_SHOW_PROPERTIES_FORM_FOR_IMAGE_MEASURE_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the measurement using angle.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_STARTS_THE_MEASUREMENT_USING_ANGLE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_STARTS_THE_MEASUREMENT_USING_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the measurement using ellipse.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_STARTS_THE_MEASUREMENT_USING_ELLIPSE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_STARTS_THE_MEASUREMENT_USING_ELLIPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the measurement using line.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_STARTS_THE_MEASUREMENT_USING_LINE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_STARTS_THE_MEASUREMENT_USING_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the measurement using lines.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_STARTS_THE_MEASUREMENT_USING_LINES {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_STARTS_THE_MEASUREMENT_USING_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo application can edit array only if array length does not exceed {0}..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_THIS_DEMO_APPLICATION_CAN_EDIT_ARRAY_ONLY_IF_ARRAY_LENGTH_DOES_NOT_EXCEED_ARG0 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_THIS_DEMO_APPLICATION_CAN_EDIT_ARRAY_ONLY_IF_ARRAY_LENGTH" +
                        "_DOES_NOT_EXCEED_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node is read-only..
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_THIS_NODE_IS_READONLY {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_THIS_NODE_IS_READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThumbnailCaption.CaptionFormat property.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_THUMBNAILCAPTIONCAPTIONFORMAT_PROPERTY {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_THUMBNAILCAPTIONCAPTIONFORMAT_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Of Measure.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_UNITS_OF_MEASURE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_UNITS_OF_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Of Measure.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_UNITS_OF_MEASURE_ALT1 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_UNITS_OF_MEASURE_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_VALUE {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual tool.
        /// </summary>
        internal static string DEMOSCOMMONCODE_IMAGING_VISUAL_TOOL {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_IMAGING_VISUAL_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string DEMOSCOMMONCODE_INFORMATION {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception: {0}.
        /// </summary>
        internal static string DEMOSCOMMONCODE_INNER_EXCEPTION_ARG0 {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_INNER_EXCEPTION_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource &apos;{0}&apos; was not found..
        /// </summary>
        internal static string DEMOSCOMMONCODE_RESOURCE_ARG0_WAS_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_RESOURCE_ARG0_WAS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string DEMOSCOMMONCODE_WARNING {
            get {
                return ResourceManager.GetString("DEMOSCOMMONCODE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation Data Collection N{0}.
        /// </summary>
        internal static string DICOMVIEWERDEMO_ANNOTATION_DATA_COLLECTION_NARG0 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_ANNOTATION_DATA_COLLECTION_NARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        internal static string DICOMVIEWERDEMO_ANNOTATIONS {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_ANNOTATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        internal static string DICOMVIEWERDEMO_ANNOTATIONS_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_ANNOTATIONS_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Annotations(*.vsab)|*.vsab.
        /// </summary>
        internal static string DICOMVIEWERDEMO_BINARY_ANNOTATIONSVSABVSAB {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_BINARY_ANNOTATIONSVSABVSAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Annotations(*.vsab)|*.vsab.
        /// </summary>
        internal static string DICOMVIEWERDEMO_BINARY_ANNOTATIONSVSABVSAB_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_BINARY_ANNOTATIONSVSABVSAB_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building annotation.
        /// </summary>
        internal static string DICOMVIEWERDEMO_BUILDING_ANNOTATION {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_BUILDING_ANNOTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn annotations on images?
        ///.
        /// </summary>
        internal static string DICOMVIEWERDEMO_BURN_ANNOTATIONS_ON_IMAGESRN {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_BURN_ANNOTATIONS_ON_IMAGESRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn annotations on images?
        ///.
        /// </summary>
        internal static string DICOMVIEWERDEMO_BURN_ANNOTATIONS_ON_IMAGESRN_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_BURN_ANNOTATIONS_ON_IMAGESRN_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated {0}.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CALCULATED_ARG0 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CALCULATED_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 125   Width 250.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_125_WIDTH_250 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_125_WIDTH_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 1280 Width 2560.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_1280_WIDTH_2560 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_1280_WIDTH_2560", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 15000 Width 30000.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_15000_WIDTH_30000 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_15000_WIDTH_30000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 1875  Width 3750.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_1875_WIDTH_3750 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_1875_WIDTH_3750", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 20   Width 40.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_20_WIDTH_40 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_20_WIDTH_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 2560 Width 5120.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_2560_WIDTH_5120 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_2560_WIDTH_5120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 30    Width 60.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_30_WIDTH_60 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_30_WIDTH_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 30000 Width 60000.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_30000_WIDTH_60000 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_30000_WIDTH_60000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 3750  Width 7500.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_3750_WIDTH_7500 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_3750_WIDTH_7500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 40   Width 80.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_40_WIDTH_80 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_40_WIDTH_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 500   Width 1000.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_500_WIDTH_1000 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_500_WIDTH_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 600  Width 1280.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_600_WIDTH_1280 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_600_WIDTH_1280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 7500  Width 15000.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_7500_WIDTH_15000 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_7500_WIDTH_15000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center 80   Width 160.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CENTER_80_WIDTH_160 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CENTER_80_WIDTH_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Info.
        /// </summary>
        internal static string DICOMVIEWERDEMO_COMPRESSION_INFO {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_COMPRESSION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string DICOMVIEWERDEMO_COPY {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current image is not DICOM frame..
        /// </summary>
        internal static string DICOMVIEWERDEMO_CURRENT_IMAGE_IS_NOT_DICOM_FRAME {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CURRENT_IMAGE_IS_NOT_DICOM_FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom VOI LUT....
        /// </summary>
        internal static string DICOMVIEWERDEMO_CUSTOM_VOI_LUT {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CUSTOM_VOI_LUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string DICOMVIEWERDEMO_CUT {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default VOI LUT.
        /// </summary>
        internal static string DICOMVIEWERDEMO_DEFAULT_VOI_LUT {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_DEFAULT_VOI_LUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DICOMVIEWERDEMO_DELETE {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string DICOMVIEWERDEMO_DELETE_ALL {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_DELETE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DemosCommonCode.Imaging.VisualToolsToolStrip.VisualTools.ZoomVisualTools.Resources.PanTool.png.
        /// </summary>
        internal static string DICOMVIEWERDEMO_DEMOSCOMMONCODEIMAGINGVISUALTOOLSTOOLSTRIPVISUALTOOLSZOOMVISUALTOOLSRESOURCESPANTOOLPNG {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_DEMOSCOMMONCODEIMAGINGVISUALTOOLSTOOLSTRIPVISUALTOOLSZOOMVISUALTO" +
                        "OLSRESOURCESPANTOOLPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM annotations cannot be converted into Vintasoft annotations but annotations can be burned on image.
        ///.
        /// </summary>
        internal static string DICOMVIEWERDEMO_DICOM_ANNOTATIONS_CANNOT_BE_CONVERTED_INTO_VINTASOFT_ANNOTATIONS_BUT_ANNOTATIONS_CAN_BE_BURNED_ON_IMAGERN {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_DICOM_ANNOTATIONS_CANNOT_BE_CONVERTED_INTO_VINTASOFT_ANNOTATIONS_" +
                        "BUT_ANNOTATIONS_CAN_BE_BURNED_ON_IMAGERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM annotations cannot be converted into Vintasoft annotations but annotations can be burned on image.
        ///.
        /// </summary>
        internal static string DICOMVIEWERDEMO_DICOM_ANNOTATIONS_CANNOT_BE_CONVERTED_INTO_VINTASOFT_ANNOTATIONS_BUT_ANNOTATIONS_CAN_BE_BURNED_ON_IMAGERN_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_DICOM_ANNOTATIONS_CANNOT_BE_CONVERTED_INTO_VINTASOFT_ANNOTATIONS_" +
                        "BUT_ANNOTATIONS_CAN_BE_BURNED_ON_IMAGERN_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM file does not contain image..
        /// </summary>
        internal static string DICOMVIEWERDEMO_DICOM_FILE_DOES_NOT_CONTAIN_IMAGE {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_DICOM_FILE_DOES_NOT_CONTAIN_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DICOMVIEWERDEMO_ERROR {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DICOMVIEWERDEMO_ERROR_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_ERROR_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}.
        /// </summary>
        internal static string DICOMVIEWERDEMO_LOADING_ARG0 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_LOADING_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossless.
        /// </summary>
        internal static string DICOMVIEWERDEMO_LOSSLESS {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_LOSSLESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossy.
        /// </summary>
        internal static string DICOMVIEWERDEMO_LOSSY {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_LOSSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnifier.
        /// </summary>
        internal static string DICOMVIEWERDEMO_MAGNIFIER {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_MAGNIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnifier Tool.
        /// </summary>
        internal static string DICOMVIEWERDEMO_MAGNIFIER_TOOL {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_MAGNIFIER_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay images are damaged..
        /// </summary>
        internal static string DICOMVIEWERDEMO_OVERLAY_IMAGES_ARE_DAMAGED {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_OVERLAY_IMAGES_ARE_DAMAGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverlayImage: {0}.
        /// </summary>
        internal static string DICOMVIEWERDEMO_OVERLAYIMAGE_ARG0 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_OVERLAYIMAGE_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page .
        /// </summary>
        internal static string DICOMVIEWERDEMO_PAGE {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        internal static string DICOMVIEWERDEMO_PAN {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Tool.
        /// </summary>
        internal static string DICOMVIEWERDEMO_PAN_TOOL {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PAN_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string DICOMVIEWERDEMO_PASTE {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation state file is saved..
        /// </summary>
        internal static string DICOMVIEWERDEMO_PRESENTATION_STATE_FILE_IS_SAVED {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PRESENTATION_STATE_FILE_IS_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation State File(*.pre)|*.pre.
        /// </summary>
        internal static string DICOMVIEWERDEMO_PRESENTATION_STATE_FILEPREPRE {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PRESENTATION_STATE_FILEPREPRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation State File(*.pre)|*.pre|All Formats(*.*)|*.*.
        /// </summary>
        internal static string DICOMVIEWERDEMO_PRESENTATION_STATE_FILEPREPREALL_FORMATS {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PRESENTATION_STATE_FILEPREPREALL_FORMATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Cancel&apos; to cancel saving..
        /// </summary>
        internal static string DICOMVIEWERDEMO_PRESS_CANCEL_TO_CANCEL_SAVING {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PRESS_CANCEL_TO_CANCEL_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Cancel&apos; to cancel saving..
        /// </summary>
        internal static string DICOMVIEWERDEMO_PRESS_CANCEL_TO_CANCEL_SAVING_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PRESS_CANCEL_TO_CANCEL_SAVING_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;No&apos; if you want save images without annotations.
        ///.
        /// </summary>
        internal static string DICOMVIEWERDEMO_PRESS_NO_IF_YOU_WANT_SAVE_IMAGES_WITHOUT_ANNOTATIONSRN {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PRESS_NO_IF_YOU_WANT_SAVE_IMAGES_WITHOUT_ANNOTATIONSRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;No&apos; if you want save images without annotations.
        ///.
        /// </summary>
        internal static string DICOMVIEWERDEMO_PRESS_NO_IF_YOU_WANT_SAVE_IMAGES_WITHOUT_ANNOTATIONSRN_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PRESS_NO_IF_YOU_WANT_SAVE_IMAGES_WITHOUT_ANNOTATIONSRN_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Yes&apos; if you want save images with burned annotations.
        ///.
        /// </summary>
        internal static string DICOMVIEWERDEMO_PRESS_YES_IF_YOU_WANT_SAVE_IMAGES_WITH_BURNED_ANNOTATIONSRN {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PRESS_YES_IF_YOU_WANT_SAVE_IMAGES_WITH_BURNED_ANNOTATIONSRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Yes&apos; if you want save images with burned annotations.
        ///.
        /// </summary>
        internal static string DICOMVIEWERDEMO_PRESS_YES_IF_YOU_WANT_SAVE_IMAGES_WITH_BURNED_ANNOTATIONSRN_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_PRESS_YES_IF_YOU_WANT_SAVE_IMAGES_WITH_BURNED_ANNOTATIONSRN_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning {0}.
        /// </summary>
        internal static string DICOMVIEWERDEMO_SCANNING_ARG0 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_SCANNING_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size={0}x{1}; PixelFormat={2}; Resolution={3}.
        /// </summary>
        internal static string DICOMVIEWERDEMO_SIZEARG0XARG1_PIXELFORMATARG2_RESOLUTIONARG3 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_SIZEARG0XARG1_PIXELFORMATARG2_RESOLUTIONARG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DICOM directory cannot be added to the series of DICOM images..
        /// </summary>
        internal static string DICOMVIEWERDEMO_THE_DICOM_DIRECTORY_CANNOT_BE_ADDED_TO_THE_SERIES_OF_DICOM_IMAGES {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_THE_DICOM_DIRECTORY_CANNOT_BE_ADDED_TO_THE_SERIES_OF_DICOM_IMAGES" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DICOM file cannot be added to the series of DICOM images because the DICOM file does not contain image..
        /// </summary>
        internal static string DICOMVIEWERDEMO_THE_DICOM_FILE_CANNOT_BE_ADDED_TO_THE_SERIES_OF_DICOM_IMAGES_BECAUSE_THE_DICOM_FILE_DOES_NOT_CONTAIN_IMAGE {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_THE_DICOM_FILE_CANNOT_BE_ADDED_TO_THE_SERIES_OF_DICOM_IMAGES_BECA" +
                        "USE_THE_DICOM_FILE_DOES_NOT_CONTAIN_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; can not be opened:
        ///\&quot;{1}\&quot;
        ///Do you want to continue anyway?.
        /// </summary>
        internal static string DICOMVIEWERDEMO_THE_FILE_ARG0_CAN_NOT_BE_OPENEDRNARG1RNDO_YOU_WANT_TO_CONTINUE_ANYWAY {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_THE_FILE_ARG0_CAN_NOT_BE_OPENEDRNARG1RNDO_YOU_WANT_TO_CONTINUE_AN" +
                        "YWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The series already contains DICOM file \&quot;{0}\&quot;..
        /// </summary>
        internal static string DICOMVIEWERDEMO_THE_SERIES_ALREADY_CONTAINS_DICOM_FILE_ARG0 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_THE_SERIES_ALREADY_CONTAINS_DICOM_FILE_ARG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF Files|*.tif;*.tiff|JPEG Files|*.jpg;*.jpeg|PNG Files|.png.
        /// </summary>
        internal static string DICOMVIEWERDEMO_TIFF_FILESTIFTIFFJPEG_FILESJPGJPEGPNG_FILESPNG {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_TIFF_FILESTIFTIFFJPEG_FILESJPGJPEGPNG_FILESPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompressed.
        /// </summary>
        internal static string DICOMVIEWERDEMO_UNCOMPRESSED {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_UNCOMPRESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string DICOMVIEWERDEMO_UNKNOWN {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string DICOMVIEWERDEMO_UNKNOWN_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_UNKNOWN_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string DICOMVIEWERDEMO_UNKNOWN_ALT2 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_UNKNOWN_ALT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Untitled).
        /// </summary>
        internal static string DICOMVIEWERDEMO_UNTITLED {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_UNTITLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Untitled).
        /// </summary>
        internal static string DICOMVIEWERDEMO_UNTITLED_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_UNTITLED_ALT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMP Annotations(*.xmp)|*.xmp.
        /// </summary>
        internal static string DICOMVIEWERDEMO_XMP_ANNOTATIONSXMPXMP {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_XMP_ANNOTATIONSXMPXMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMP Annotations(*.xmp)|*.xmp.
        /// </summary>
        internal static string DICOMVIEWERDEMO_XMP_ANNOTATIONSXMPXMP_ALT1 {
            get {
                return ResourceManager.GetString("DICOMVIEWERDEMO_XMP_ANNOTATIONSXMPXMP_ALT1", resourceCulture);
            }
        }
    }
}
